const player = {
  id: 4,
  role: 2,
  telegram_id: 984618,
  telegram_username: "Чебупеля",
  voevoda_id: 1,
  activity: False,
  comment: "",
  stats: {
    id: 8407373,
    name: "Walania",
    level: 6,
    clan: 522,
    umka_knight: 0,
    umka_necro: 0,
    umka_mag: 0,
    umka_elf: 0,
    umka_barbar: 5,
    umka_black_elf: 0,
    umka_demon: 0,
    umka_dwarf: 0,
    umka_step_barb: 0,
    umka_pharaon: 0,
    gild_hunt: 4,
    gild_work: 0,
    gild_card: 0,
    gild_thief: 0,
    gild_ranger: 0,
    gild_mers: 0,
    gild_tactic: 0,
    gild_gard: 0,
    gild_seekers: 0,
    gild_leader: 0,
    gild_blacksmith: 0,
    gild_gunsmith: 0,
    person_id: None,
  },
  presets: [
    { id: 2, person_id: 4, preset: { id: 3, voevoda_id: 1, fraction: 0, name: "Лысарь", description: "Обычный лысарь" }, play_preset: False },
    { id: 3, person_id: 4, preset: { id: 4, voevoda_id: 1, fraction: 4, name: "Барба", description: "Барбар" }, play_preset: False },
    { id: 7, person_id: 4, preset: { id: 7, voevoda_id: 1, fraction: 7, name: "Кто-то", description: "Описание чего то" }, play_preset: False },
  ],
};
