# Generated by Django 5.1.1 on 2024-09-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoevodaModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('clan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.clansmodel', verbose_name='Клан')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(1, 'Воевода'), (2, 'Помощник воеводы'), (100, 'Игрок')], default=100, verbose_name='Роль')),
                ('telegram_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(max_length=100)),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.playersmodel', verbose_name='Игровой персонаж')),
                ('voevoda_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.voevodamodel', verbose_name='Закреплен за воеводой')),
            ],
        ),
    ]
