# Generated by Django 5.1.1 on 2024-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0002_voevodamodel_personsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personsmodel',
            options={'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='playersmodel',
            options={'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='voevodamodel',
            options={'verbose_name_plural': 'Воеводы'},
        ),
        migrations.AddField(
            model_name='voevodamodel',
            name='tmp_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
