# Generated by Django 5.1.1 on 2024-09-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0003_alter_personsmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fraction', models.IntegerField(choices=[(0, 'Рыцарь'), (1, 'Некромант'), (2, 'Маг'), (3, 'Эльф'), (4, 'Варвар'), (5, 'Темный эльф'), (6, 'Демон'), (7, 'Гном'), (8, 'Степной варвар'), (9, 'Фараон')])),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('voevoda_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.voevodamodel', verbose_name='Закреплен за воеводой')),
            ],
            options={
                'verbose_name_plural': 'Пресеты',
            },
        ),
    ]
