# Generated by Django 5.1.1 on 2024-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0004_presetsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presetsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voevodamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
