# Generated by Django 5.1.1 on 2024-09-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0005_alter_personsmodel_id_alter_presetsmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsmodel',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='personsmodel',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.playersmodel', verbose_name='Игровой персонаж'),
        ),
        migrations.AlterField(
            model_name='personsmodel',
            name='voevoda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.voevodamodel', verbose_name='Закреплен за воеводой'),
        ),
        migrations.AlterField(
            model_name='presetsmodel',
            name='voevoda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.voevodamodel', verbose_name='Закреплен за воеводой'),
        ),
    ]
