# Generated by Django 5.1.1 on 2024-09-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0006_personsmodel_activity_alter_personsmodel_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsmodel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к игроку'),
        ),
        migrations.CreateModel(
            name='PersonPresetModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('play_preset', models.BooleanField(default=False, verbose_name='Играет за пресет?')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.personsmodel', verbose_name='Игрок')),
                ('preset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.presetsmodel', verbose_name='Пресет')),
            ],
            options={
                'verbose_name_plural': 'Пресеты игроков',
            },
        ),
    ]
