# Generated by Django 5.1.1 on 2024-09-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0007_personsmodel_comment_personpresetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.IntegerField(choices=[(1, 'Атака на предприятие'), (2, 'Защита предприятия')], default=1, verbose_name='Тип боя')),
                ('result', models.IntegerField(choices=[(1, 'Победа стороны атаки'), (2, 'Победа стороны защиты')], verbose_name='Результат')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('attack_1_pers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_1_fights', to='voevoda_app.playersmodel', verbose_name='1-й игрок атаки')),
                ('attack_1_pers_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_1_presets', to='voevoda_app.presetsmodel', verbose_name='пресет 1-го игрока атаки')),
                ('attack_2_pers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_2_fights', to='voevoda_app.playersmodel', verbose_name='2-й игрок атаки')),
                ('attack_2_pers_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_2_presets', to='voevoda_app.presetsmodel', verbose_name='пресет 2-го игрока атаки')),
                ('defence_1_pers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defence_1_fights', to='voevoda_app.playersmodel', verbose_name='1-й игрок защиты')),
                ('defence_1_pers_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defence_1_presets', to='voevoda_app.presetsmodel', verbose_name='пресет 1-го игрока защиты')),
                ('defence_2_pers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defence_2_fights', to='voevoda_app.playersmodel', verbose_name='2-й игрок защиты')),
                ('defence_2_pers_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defence_2_presets', to='voevoda_app.presetsmodel', verbose_name='пресет 2-го игрока защиты')),
                ('voevoda_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.voevodamodel', verbose_name='Воевода')),
            ],
            options={
                'verbose_name_plural': 'Пресеты игроков',
            },
        ),
    ]
