# Generated by Django 5.1.1 on 2024-09-15 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0008_fightsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
