# Generated by Django 5.1.1 on 2024-09-15 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0009_fightsmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fightsmodel',
            options={'verbose_name_plural': 'Битвы'},
        ),
        migrations.AlterField(
            model_name='fightsmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Атака'), (2, 'Защита')], default=1, verbose_name='Тип боя'),
        ),
        migrations.CreateModel(
            name='FightEventModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.IntegerField(choices=[(1, 'Атака'), (2, 'Защита')], default=1, verbose_name='Тип боя')),
                ('state', models.IntegerField(choices=[(1, 'Первоначальный сбор'), (2, 'Выбор бойцов'), (3, 'Идет бой'), (4, 'Завершен')])),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voevoda_app.clansmodel', verbose_name='Противник')),
                ('voevoda_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voevoda_app.voevodamodel', verbose_name='Воевода')),
            ],
            options={
                'verbose_name_plural': 'Боевые Ивенты',
            },
        ),
    ]
