# Generated by Django 5.1.1 on 2024-11-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voevoda_app', '0011_alter_fighteventmodel_state_invitemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightsmodel',
            name='loss_persent',
            field=models.IntegerField(default=0, verbose_name='% потерь'),
        ),
        migrations.AlterField(
            model_name='invitemodel',
            name='state',
            field=models.IntegerField(choices=[(1, 'Отправлено'), (2, 'Принято'), (3, 'Отказ'), (4, 'Выбран на бой')], default=1),
        ),
        migrations.AlterField(
            model_name='personsmodel',
            name='telegram_username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voevodamodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='voevodamodel',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
